//
//     Generated by class-dump 3.5 (64 bit) & modified by hand
//
#import <Cocoa/Cocoa.h>

@class AlertButton, AlertDeclineButton, AlertIconButton, AlertPopUpButton;

@interface LyncCommonAlertWindowController : NSObject
{
    NSImageView *backgroundImageView_;
    NSImageView *contactPhotoImageView_;
    NSImageView *bossAdminPresenceImageView_;
    NSImageView *dividerImageView_;
    AlertIconButton *acceptButton_;
    AlertDeclineButton *closeButton_;
    AlertButton *secondaryActionButton_;
    AlertPopUpButton *secondaryActionPopUpButton_;
    NSTextField *contactNameField_;
    NSTextField *contactSecondaryDetailField_;
    NSTextField *contextField_;
    NSTextField *secondContextField_;
    NSTextField *bossAdminNameField_;
    struct MacToastWnd *toastWnd_;
    BOOL isTimeoutProcessed_;
}

+ (void)hotkeyDown:(id)arg1;
+ (id)attributesForStringType1;
+ (id)attributesForStringType2;
+ (id)attributesForStringType3;
- (void)setBackgroundImage;
- (id)initWithToastWnd:(struct MacToastWnd *)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)showWindow:(id)arg1;
- (float)defaultDurationForFindingPosition;
- (void)setToastWnd:(struct MacToastWnd *)arg1;
- (void)attemptShow:(id)arg1;
- (void)onTimeout;
- (void)closeWindow;
- (void)setContactName:(id)arg1;
- (void)setContactSecondaryDetail:(id)arg1;
- (void)setContext:(id)arg1;
- (void)setSecondContext:(id)arg1;
- (void)setBossAdminName:(id)arg1;
- (void)setSecondaryActionButtonWithTitle:(id)arg1 popUpMenu:(id)arg2;
- (void)setContactPhotoAndPresence:(id)arg1;
- (void)setBossAdminPresence:(id)arg1;
- (id)modalityIcon;
- (void)setCloseButton:(id)arg1;
- (void)adjustTextFieldsPosition;
- (void)acceptButtonClicked:(id)arg1;
- (void)closeButtonClicked:(id)arg1;
- (void)secondaryActionButtonClicked:(id)arg1;
- (void)secondaryActionPopUpButtonClicked:(id)arg1;
- (id)bossAdminNameField;
- (id)secondContextField;
- (id)contextField;
- (id)contactSecondaryDetailField;
- (id)contactNameField;
- (id)secondaryActionPopUpButton;
- (id)secondaryActionButton;
- (id)closeButton;
- (id)acceptButton;

@end

